src/ShopBundle/Entity/User.php
<?php

namespace ShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * User
 */
class User extends BaseUser
{
    /**
     * @var int
     */
    protected $id;
    
    protected $isAutonomo;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var \ShopBundle\Entity\Cart
     */
    private $cart;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $orderInfos;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();
    }

    public function __toString() {
        return strval($this->id);
    }
    /**
     * Set cart
     *
     * @param \ShopBundle\Entity\Cart $cart
     * @return User
     */
    public function setCart(\ShopBundle\Entity\Cart $cart = null)
    {
        $this->cart = $cart;

        return $this;
    }

    /**
     * Get cart
     *
     * @return \ShopBundle\Entity\Cart 
     */
    public function getCart()
    {
        return $this->cart;
    }

    /**
     * Add orderInfos
     *
     * @param \ShopBundle\Entity\OrderInfo $orderInfos
     * @return User
     */
    public function addOrderInfo(\ShopBundle\Entity\OrderInfo $orderInfos)
    {
        $this->orderInfos[] = $orderInfos;

        return $this;
    }

    /**
     * Remove orderInfos
     *
     * @param \ShopBundle\Entity\OrderInfo $orderInfos
     */
    public function removeOrderInfo(\ShopBundle\Entity\OrderInfo $orderInfos)
    {
        $this->orderInfos->removeElement($orderInfos);
    }

    /**
     * Get orderInfos
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getOrderInfos()
    {
        return $this->orderInfos;
    }

    public function getOrderInfoSum()
    {
        $orderInfos = $this->orderInfos;
        $sum = 0;
        foreach($orderInfos as $orderInfo)
        {
            $sum += $orderInfo->getTotalPrice();
        }

        return $sum;
    }

    /**
     * Set isAutonomo
     *
     * @param boolean $isAutonomo
     * @return User
     */
    public function setIsAutonomo($isAutonomo)
    {
        $this->isAutonomo = $isAutonomo;

        return $this;
    }

    /**
     * Get isAutonomo
     *
     * @return boolean 
     */
    public function getIsAutonomo()
    {
        return $this->isAutonomo;
    }
    /**
     * @var array
     */
    protected $timesCategory;


    /**
     * Set timesCategory
     *
     * @param array $timesCategory
     * @return User
     */
    public function setTimesCategory($timesCategory)
    {
        $this->timesCategory = $timesCategory;

        return $this;
    }

    /**
     * Get timesCategory
     *
     * @return array 
     */
    public function getTimesCategory()
    {
        return $this->timesCategory;
    }

    public function getTimes()
    {
        $timesCategory = $this->timesCategory;
        $array = unserialize($timesCategory);

        return $array;
    }
}

src/ShopBundle/Resources/views/BackEnd/analysis.html.twig
{% extends 'ShopBundle:BackEnd:index.html.twig' %}

{% block menuslide %}
    <ul class="nav nav-sidebar">
        <li><a href="{{ path('shop_homepage_admin') }}"><i class="fa fa-tachometer" aria-hidden="true"></i> &nbsp;Visión Genenal  <span class="sr-only">(current)</span></a></li>
        <li><a href="#"><i class="fa fa-info" aria-hidden="true"></i> &nbsp;&nbsp;&nbsp;&nbsp;Informe</a></li>
        <li class="active"><a href="{{ path('shop_analysis') }}"><i class="fa fa-bar-chart" aria-hidden="true"></i>&nbsp; Análisis</a></li>
    </ul>
    <ul class="nav nav-sidebar">
        <li><a href="{{ path('user_index') }}"><i class="fa fa-users" aria-hidden="true"></i> &nbsp;&nbsp;Gestión de Usuarios</a></li>
        <li><a href="{{ path('category_index') }}"><i class="fa fa-columns" aria-hidden="true"></i> &nbsp;&nbsp;Gestión de Categorías</a></li>
        <li><a href="{{ path('product_index') }}"><i class="fa fa-female" aria-hidden="true"></i> &nbsp;&nbsp;&nbsp;Gestión de Productos</a></li>
        <li><a href="{{ path('select_new') }}"><i class="fa fa-heart" aria-hidden="true"></i> &nbsp;&nbsp;Selección Nuevos</a></li>
        <li><a href="{{ path('sale_index') }}"><i class="fa fa-bell" aria-hidden="true"></i> &nbsp;&nbsp;Gestión de Ofertas</a></li>
        <li><a href="{{ path('orderinfo_index') }}"><i class="fa fa-credit-card" aria-hidden="true"></i> &nbsp;&nbsp;Gestión de Pedidos</a></li>
    </ul>
{% endblock %}

{% block content %}
    <h1 class="sub-header">Análisis de comportamiento de usuario</h1>
    <br>
    <span style="font-size: 24px;font-weight:600;margin-right:100px;">Hot Products</span>
    <a href="{{ path('shop_analysis_clearProduct') }}" class="button button-inverse">Limpiado</a>
    <div class="col-md-12">
        <canvas id="myChart2" width="800" height="350"></canvas>
    </div>
    <br><br><br>
    <span style="font-size: 24px;font-weight:600;margin-right:100px;">Hot Categorias</span>
    <a href="{{ path('shop_analysis_clearCategory') }}" class="button button-inverse">Limpiado</a>
    <div class="col-md-12">
        <canvas id="myChart3" width="800" height="350"></canvas>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        var ctz = document.getElementById("myChart2");

        var myChart2 = new Chart(ctz, {
            type: 'bar',
            data: {
                labels: [
                    {% for product in products|slice(0, 9) %}
                    "{{ product.code }}"
                    {% if not loop.last %},{% endif %}
                    {% endfor %}
                ],
                datasets: [{
                    label: 'Veces de Visto',
                    data: [
                        {% for product in products|slice(0, 9) %}
                        "{{ product.times }}"
                        {% if not loop.last %},{% endif %}
                        {% endfor %}
                    ],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true,
                            stepSize: 1
                        }
                    }]
                }
            }
        });

        var cta = document.getElementById("myChart3");

        var myChart3 = new Chart(cta, {
            type: 'bar',
            data: {
                labels: [
                    {% for category in categories|slice(0, 9) %}
                    "{{ category.categoryNameEs }}"
                    {% if not loop.last %},{% endif %}
                    {% endfor %}
                ],
                datasets: [{
                    label: 'Veces de Visto',
                    data: [
                        {% for category in categories|slice(0, 9) %}
                        "{{ category.times }}"
                        {% if not loop.last %},{% endif %}
                        {% endfor %}
                    ],
                    backgroundColor: [
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)'
                    ],
                    borderColor: [
                        'rgba(54, 162, 235, 1)',
                        'rgba(255,99,132,1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true,
                            stepSize: 1
                        }
                    }]
                }
            }
        });
    </script>
{% endblock %}

src/ShopBundle/Resources/views/BackEnd/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/shop/css/dashboard.css') }}" rel="stylesheet">
{% endblock %}
{% block body %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">TannaModa Consola de Gestión </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ path('shop_homepage') }}">Index</a></li>
                    <li><a href="#">Whatsapp: 691956647</a></li>
                    <li><a href="#">Wechat: 1878118</a></li>
                </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" id="search" placeholder="Buscar...">
                </form>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                {% block menuslide %}{% endblock %}
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.js"></script>
    <script src="{{ asset('bundles/shop/js/dashboard.js') }}"></script>
{% endblock %}

src/ShopBundle/Resources/views/BackEnd/overview.html.twig
{% extends 'ShopBundle:BackEnd:index.html.twig' %}

{% block menuslide %}
    <ul class="nav nav-sidebar">
        <li class="active"><a href="{{ path('shop_homepage_admin') }}"><i class="fa fa-tachometer" aria-hidden="true"></i> &nbsp;Visión Genenal  <span class="sr-only">(current)</span></a></li>
        <li><a href="#"><i class="fa fa-info" aria-hidden="true"></i> &nbsp;&nbsp;&nbsp;&nbsp;Informe</a></li>
        <li><a href="{{ path('shop_analysis') }}"><i class="fa fa-bar-chart" aria-hidden="true"></i>&nbsp; Análisis</a></li>
    </ul>
    <ul class="nav nav-sidebar">
        <li><a href="{{ path('user_index') }}"><i class="fa fa-users" aria-hidden="true"></i> &nbsp;&nbsp;Gestión de Usuarios</a></li>
        <li><a href="{{ path('category_index') }}"><i class="fa fa-columns" aria-hidden="true"></i> &nbsp;&nbsp;Gestión de Categorías</a></li>
        <li><a href="{{ path('product_index') }}"><i class="fa fa-female" aria-hidden="true"></i> &nbsp;&nbsp;&nbsp;Gestión de Productos</a></li>
        <li><a href="{{ path('select_new') }}"><i class="fa fa-heart" aria-hidden="true"></i> &nbsp;&nbsp;Selección Nuevos</a></li>
        <li><a href="{{ path('sale_index') }}"><i class="fa fa-bell" aria-hidden="true"></i> &nbsp;&nbsp;Gestión de Ofertas</a></li>
        <li><a href="{{ path('orderinfo_index') }}"><i class="fa fa-credit-card" aria-hidden="true"></i> &nbsp;&nbsp;Gestión de Pedidos</a></li>
    </ul>
{% endblock %}

{% block content %}
    <h1 class="page-header">Dashboard</h1>
    <br>
    <div class="row">
        <div class="col-sm-6 col-md-3 col-lg-3">
            <div class="panel user">
                <a href="{{ path('user_index') }}"><span>{{ numUser }} </span>Usuarios</a>
            </div>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-3">
            <div class="panel comment">
                <a href=""><span>{{ viewsToday }} </span>Vistas Hoy</a>
            </div>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-3">
            <div class="panel page">
                <a href="{{ path('orderinfo_index') }}"><span>{{ numOrder }} </span>Pedidos</a>
            </div>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-3">
            <div class="panel post">
                <a href="{{ path('product_index') }}"><span>{{ numProduct }} </span>Productos</a>
            </div>
        </div>
    </div>

    <br>
    <h1 class="sub-header">Tabla de Informaciones de Pedidos</h1>
    <div class="row">
        <div class="col-md-4 col-lg-4">
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
        <div class="data" style="display: none">
            {% for day6Order in day6Orders %}
                <div id="day{{ loop.index }}order">{% if day6Order == null %}0{% else %}{{ day6Order }}{% endif %}</div>
            {% endfor %}
        </div>
        <div class="col-md-6 col-md-offset-1 col-lg-6 col-lg-offset-1">
            <div class="table-responsive" style="position: relative; top: 25px;">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Nuevos Pedidos</th>
                        <th>Usuario</th>
                        <th>Importe total</th>
                        <th>Ciudad</th>
                        <th>Tiempo de generación</th>
                    </tr>
                    </thead>
                    <tbody>
                {% for order in orders %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.user.username }}</td>
                        <td>{{ order.totalPrice|number_format(2, '.', ',') }} €</td>
                        <td>{{ order.receiverCity }}</td>
                        <td>{% if order.orderDate %}{{ order.orderDate|date('Y-m-d H:i') }}{% endif %}</td>
                    </tr>
                {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br>
    <h2 class="sub-header">Tabla de Informaciones de Usuarios</h2>
    <div class="row">
        <div class="col-md-6 col-lg-6">
            <div class="table-responsive" style="position: relative; top: 25px;">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Nuevo Registrado</th>
                        <th>Nombre</th>
                        <th>Correo Electrónico</th>
                        <th>Último Acceso</th>
                    </tr>
                    </thead>
                    <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>{% if user.lastLogin %}{{ user.lastLogin|date('Y-m-d H:i:s') }}{% endif %}</td>
                    </tr>
                {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-4 col-md-offset-1 col-lg-4 col-lg-offset-1">
            <canvas id="myChart1" width="400" height="400"></canvas>
        </div>
    </div>
    <br><br><br>
{% endblock %}